### ISSUE TITLE
Create a shared slider component

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/shared-react-components#15]
**What's wrong**
We want to make a reusable PSASlider component that can be shared between the different applications.  

**What done looks like**
when we have a shared PSASlider component that can be implemented into seedCalc and Selector if needed.  More applications will come later. 

**Where the changes need to be made**
Any place we are currently using a slider bar we will want to replace with this component.

**Comment by shannon-gt** [comment]
Based on user feedback we might want to replace this with a different interaction, but I think we can keep this for now!
